/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Note { 'id' : bigint, 'title' : string, 'content' : string }
export interface Task {
  'id' : bigint,
  'completed' : boolean,
  'description' : string,
}
export interface _SERVICE {
  'addTask' : ActorMethod<[string], bigint>,
  'createNote' : ActorMethod<[string, string], bigint>,
  'deleteNote' : ActorMethod<[bigint], undefined>,
  'deleteTask' : ActorMethod<[bigint], undefined>,
  'getAllNotes' : ActorMethod<[], Array<Note>>,
  'getAllTasks' : ActorMethod<[], Array<Task>>,
  'getNote' : ActorMethod<[bigint], Note>,
  'getNotesSortedByTitle' : ActorMethod<[], Array<Note>>,
  'toggleTaskCompletion' : ActorMethod<[bigint], undefined>,
  'updateNote' : ActorMethod<[bigint, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];