/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Note = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
});
export const Task = IDL.Record({
  'id' : IDL.Nat,
  'completed' : IDL.Bool,
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  'addTask' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'createNote' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'deleteNote' : IDL.Func([IDL.Nat], [], []),
  'deleteTask' : IDL.Func([IDL.Nat], [], []),
  'getAllNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
  'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getNote' : IDL.Func([IDL.Nat], [Note], ['query']),
  'getNotesSortedByTitle' : IDL.Func([], [IDL.Vec(Note)], ['query']),
  'toggleTaskCompletion' : IDL.Func([IDL.Nat], [], []),
  'updateNote' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Note = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
  });
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'completed' : IDL.Bool,
    'description' : IDL.Text,
  });
  
  return IDL.Service({
    'addTask' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'createNote' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'deleteNote' : IDL.Func([IDL.Nat], [], []),
    'deleteTask' : IDL.Func([IDL.Nat], [], []),
    'getAllNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
    'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getNote' : IDL.Func([IDL.Nat], [Note], ['query']),
    'getNotesSortedByTitle' : IDL.Func([], [IDL.Vec(Note)], ['query']),
    'toggleTaskCompletion' : IDL.Func([IDL.Nat], [], []),
    'updateNote' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };